const LOCAL_STORAGE_USERNAME_KEY = 'MinesweeperUserNameByDisembow';
const LOCAL_STORAGE_RESULTS_KEY = 'MinesweeperResultsByDisembow';

const MAIN_BG_COLOR = '#bdbdbd';
const BORDER_COLOR_BRIGHT = '#ffffff';
const BORDER_COLOR_SHADOWED = '#7b7b7b';

export {
  LOCAL_STORAGE_USERNAME_KEY,
  LOCAL_STORAGE_RESULTS_KEY,
  MAIN_BG_COLOR,
  BORDER_COLOR_BRIGHT,
  BORDER_COLOR_SHADOWED,
};
